### PR TITLE
Fix spotify

### PR DESCRIPTION
**Pull request by jesus2099**
Hi @Shuunen.
I was looking for a Spotify importer and found yours.
However it didn't work any more, apparently.

There were a few typos that I had to fix for it to work.

There are two versions of Spotify.

My Chromium on Raspbian sees a simple web page.
I slightly updated your script to make it work in that.

My other browsers (Vivaldi and Firefox) see a more complex web page (for the same Spotify URL).
I changed the script so that it works in both types of page.

---

As a sidenote (I did not include any related change in this PR), I think it's incorrect to take ©&℗ labels as as release labels.
They are © copyright and ℗ phonographic copyright relationships.
We could set them in `annotation` instead of `labels.0.name`.

---

Sidenote 2: I found https://etc.marlonob.info/atisket/ that can import with sub-second (millisecond) track durations and with real release labels

### CODE REVIEW

**Comment by jesus2099** [comment]
@Shuunen, could you launch guardrails on master to see if this warning was not already there?
I just did some small regexp change only.
I cannot access guardrails report to know what is the issue with https://github.com/Shuunen/user-scripts/pull/20/commits/dce8e5f2482f95c45709ead365c4e47cc2b04a25#diff-aa94bc1502f50f91dc41ac9483ae7a2cR30 . :)

**Comment by Shuunen** [comment]
@jesus2099 hey thanks for contributing 😄 

looks like there is another regex issue on master, but also one on this PR, I'll fix it

**Comment by Shuunen** [comment]
@jesus2099 it appears that Guardrails added this security because of potentially catastrophic regex performance known issues : 

on the master branch I fix the problem by turning :  `/eur (\d+,\d\d)\/(\w+)(\s\w)?/i` into `/eur (\d+,\d\d)\/(\w+)\s?(\w*)/i`

I have to admit multiple things with this "fix" : 
1. I installed a lint plugin to detect the same issue that Guardrails catch
2. I tried to tweak my regex until lint reach inner peace & hapiness
3. the both regex are not doing exactly the same work, but both were doing what I needed in this piece of code

So you'll need to rebase your work from the new master, then `npm install`, then fix the lint errors... sorry for the conflicts 😅

**Comment by Shuunen** [comment]
@jesus2099  I just tested here https://regex101.com/r/hOSJi5/3 that `/[\d\s©℗]+(.*)/` seems to cover our use case and does not raise any issues, what do think ?

**Comment by jesus2099** [comment]
It's excellent, this new expression!
Do I just use that in a new commit and let's see if it's better?

What's your browser by the way?
Do you see the simplified or the full Spotify pages?

**Comment by jesus2099** [comment]
> So you'll need to rebase your work from the new master, then npm install, then fix the lint errors... sorry for the conflicts 😅

Hmmm, I don't know that stuff yet, but I'll try...

**Comment by jesus2099** [comment]
I have now merged your master in my branch.
I have then run `npm install` on the root of my forked repo, on my updated branch.
But it seems I don't have recent enough version of `npm`?


```
pi@raspberrypi:~/git/Shuunen_user-scripts $ npm install
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 high, 1 low. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.19 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
added 222 packages from 151 contributors in 254.723s
```

I don't know how this works nor what `npm`is. (._.?)

**Comment by jesus2099** [comment]
I randomly tried `npm test` and I get no errors, indeed.
If I put the previous regular expression, it's a:

```
/home/pi/git/Shuunen_user-scripts/src/mb-import-from-spotify.user.js
  30:81  error  Unsafe regular expression  unicorn/no-unsafe-regex
```

But a strange thing is that this `npm` thing insists on removing some semicolons `;` from the code.
For me it's not clean but I guess if you use `npm` everytime you change your code, I should commit that, anyway.

**Comment by Shuunen** [comment]
- For the node & npm version I have node 12 & npm 6 but I'm surprised it's not working on node 10
- I can't merge this merge request due to conflicts, 2 solutions here : 

1. you rebase your work onto the master branch
or
2. I can add your changes directly to master & close this MR

Let me know what you prefer 👍

**Comment by jesus2099** [comment]
Can't you merge with GitHub, it sees no conflicts, doesn't it?

2020-07-09-212903_805x275_scrot
I see: _This branch has no conflicts with the base branch_

But if you prefer your option 1, please explain a little bit more.
Isn't it what I did or tried to do with f66f5e3da774c24e6d555f9bd10067442b90dc64?
By _you **rebase your work onto the master branch**_, you mean I should checkout... my fork's master? and do a merge rebase of my fix-spotify branch? I don't understand very much. I am not a pro at git...

**Comment by Shuunen** [comment]
Hum right the rebase option merge was not available : 
image
But the other method are, so no big deal here, I'll merge this without rebase

**Comment by Shuunen** [comment]
Thanks again for contributing 👍 😃

**Comment by Shuunen** [comment]
By the way I'm using Chrome on Windows 10 x64 , how do I know if i'm seeing the simple or full page on the example link : https://open.spotify.com/album/0skg1dUrsqiN21tfxC8a52 ?

image

**Pull request merged**
